# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'simpleGolfApp.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sqlite3
from PyQt5 import QtCore, QtGui, QtWidgets
from fittingWidget import fToolWin
from handicapWidget import Ui_Form
from handicapTracker import handiTracker


class Ui_MainWindow(object):



    def openHandicapTracker(self): #change this to the tracker, change class name on the tracker and function name
        self.window = QtWidgets.QMainWindow()
        self.ui = handiTracker()
        self.ui.setupUi(self.window)
        self.window.show()

    def openFittingWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = fToolWin()
        self.ui.setupUi(self.window)
        self.window.show()

    def openHandicapWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Form()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(80, 70, 561, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.fittingTool = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.openFittingWindow())
        self.fittingTool.setGeometry(QtCore.QRect(90, 240, 211, 131))
        self.fittingTool.setObjectName("fittingTool")
        self.handiCalc = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.openHandicapWindow())
        self.handiCalc.setGeometry(QtCore.QRect(480, 240, 211, 131))
        self.handiCalc.setObjectName("handiCalc")
        self.handicapTrackerBtn = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.openHandicapTracker())
        self.handicapTrackerBtn.setGeometry(QtCore.QRect(280, 420, 211, 131))
        self.handicapTrackerBtn.setObjectName("handicapTrackerBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "fitting and handicap tool"))
        self.title.setText(_translate("MainWindow", "Golf Tool"))
        self.fittingTool.setText(_translate("MainWindow", "Golf Club Fitting Tool"))
        self.handiCalc.setText(_translate("MainWindow", "Handicap Calculator"))
        self.handicapTrackerBtn.setText(_translate("MainWindow", "Handicap Tracker"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())